### ISSUE TITLE
HACS still claims component is archived and deleted despite recent release/update

### ISSUE THREAD

**Issue by taw123** [custom-components/sensor.sonarr_upcoming_media#30] opened 2024-02-08 18:25 UTC
**Describe the Bug**
Looooooong time ago installed and set up Sonarr Upcoming sensor to feed upcoming media card. A while back HACS claimed integration was deleted/archived (std msg). Of course sensor continued to work and I lived with the warning in the UI, while occasionally looking/hoping for an update.

Fast forward to this week when I found while getting ready for 2024.2 that you had updated this...  <much applause> I thought I would finally be rid of the msgs after manually downloading and updating the component.

**The Error**
```
Removed repository 'custom-components/sensor.sonarr_upcoming_media'
Repository is archived
```

Unfortunately HA still complains about the integration being deleted/archived. I tried deleting the integration from my HACS install and then RE-ADDING the repo manually (by url). Same result...

Don't believe the issue is mine though an engineer for many years don't have much of an understanding of HA internals or HACS internals so perhaps there is something more at play here besides what I am hoping is just a matter of getting qualified in the HAC Store? 

Though if I DID understand how HACS works that SHOULDN'T be an issue if I MANUALLY added your GitHub repo into HACS, right? Private (non "store" "certified/qualified") repos CAN be added via HACS to HA for version control right? And in that case there shouldn't be any messages deprivation/archive marking (again if  my shaky understanding is indeed correct) 

Thanks for any insights you might have on this and your plans for your equally useful RADARR sensor (didn't want to your time opening an exact duplicate of this issue on that component as well, since I suspect one answer will cover both)

Version: **HA Core 2024.2.0 -- Docker**

**Comment by mkanet** [comment] 2024-02-08 20:35
Hi, this integration as well as other similar ones _used_ to be on HACS a long time ago.  Back then, it was a lot easier to add custom integrations to HACS.  I've already added almost all the changes necessary for them to be compliant with the latest HACS requirements.  

I'm still waiting for the below PR's (Home Assistant Brands repo) to be approved/merged to pass HACS workflow-based validation.   After that happens, there is one last step..  to add these integrations's URLs to the official HACS repo for them to be searchable.

https://github.com/home-assistant/brands/pull/5180
https://github.com/home-assistant/brands/pull/5181

Hang in there.  I will do this as soon as it's possible.

**Comment by taw123** [comment] 2024-02-10 18:33
No worries. Thanks and thanks again for all your efforts, it's truly appreciated.

I was just trying to understand why it was that even after I MANUALLY added your repo to HACS that it still complained. My understanding is much like repo management in other platforms MANUAL adds would bypass any kind of "official" HACS certification/qualification management hurdles. Perhaps that's NOT how things work in HACS, or something that was lingering from the initial version wasn't deleted when I removed and then later re-added the integration.

Regardless thanks having gotten back to me and keeping these integrations alive.

**Comment by mkanet** [comment] 2024-03-20 19:52
Hi @douginoz , I'm also excited about bringing back the original integrations for Upcoming Media Card and also Upcoming Media card itself.  They aren't _yet_ available in the current Home Assistant version.  If you want to start using them now, you will need access to your `/config/custom_components` folder for your Home Assistant installation (either via Samba Share or SSH).  

Below, is an example of how you would do it.  You should backup the existing files before deleting anything; just in case something goes wrong.  You can always put the files/folder back exactly how it was and reboot to return it back to how it was.

Instructions for the official latest version of `sonarr_upcoming_media card`:

1. Access your Home Assistant Samba share: Navigate to `\\your_homeassistant_hostname\config\custom_components` on your computer. Replace `your_homeassistant_hostname` with your actual Home Assistant hostname.
2. Visit the GitHub page for Sonarr_upcoming_media: https://github.com/custom-components/sensor.sonarr_upcoming_media
3. Click the "Code" button and select "Download ZIP" to download the `sensor.sonarr_upcoming_media_master.zip` file.
4. Unzip the downloaded file on your computer.
5. Delete the existing `sonarr_upcoming_media` folder within the `custom_components` directory on the Samba share.
6. Copy the unzipped `sensor.sonarr_upcoming_media` folder into the `custom_components` directory on the Samba share.
7. Restart Home Assistant to apply the changes.

**Comment by douginoz** [comment] 2024-03-20 20:02
That's awesome!  I guess I was lucky to stumble across that whole system only a couple of days ago. It all seems to work well apart from songs missing new features so it's been a good experience so far. I'll try following your steps to get this integrated. Let me know if there are other similar steps available for the other modules or the main ones (to enable deep links for instance!).  

Thanks for your ongoing commitment to this project.

**Comment by douginoz** [comment] 2024-03-20 21:02
> 
>     6. Copy the unzipped `sensor.sonarr_upcoming_media` folder into the `custom_components` directory on the Samba share.
> 
>     7. Restart Home Assistant to apply the changes.

That doesn't appear to work.  I think what you meant to say is to copy the subdirectory "sonarr_upcoming_media" that's in the "sensor.sonarr_upcoming_media-master folder into the custom_components folder.  That's where the older sonarr_upcoming_media folder was.  Otherwise the 'sensor.sonar_upcoming_media' entity is gone.

**Comment by mkanet** [comment] 2024-03-21 02:33
Sorry, my manual installation instructions weren't intended to be followed verbatim.  It was just a general guide. 

I would make sure that your sonarr_upcoming_media integration (or whatever integration you're using) is providing deep_link for example:
![image](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/811008/785542f7-98d6-4d9c-8011-f30620845236)

Yeah the readme instructions are quite old.  I need to update it.  It's not required to append a version number when manually adding the latest `upcoming-media-card` to your home assistant instance.  All you should need to do after replacing the appropriate source file(s) is reboot Home Assistant and **delete your web browser's cache**.  Not deleting the browser cache is very common oversight, I sometimes forget to do it too.  **Does your mouse cursor change when hovering it over each Sonarr TV episode** (after you delete your web browser's cache)?  Deep_links hyperlinks are also compatible with touch screen mobile devices too.  Hopefully, upgrading will be a lot easier once these repos are available again on HACS.

BTW:  I _just_ updated Upcoming Media Card with a new tooltip feature today.  I also updated the documentation for how to enable tooltips.  Dont forget to download Upcoming Media Card again to get this new feature (along with some bugfixes).  Just copy the file(s), reboot; then, finally delete your web browser's cache.  After doing this, does tooltips work for you?

**Comment by douginoz** [comment] 2024-03-21 04:39
I've removed the ?v=0.4.4 from the end of the line in ui-lovelace.
I copied across the latest Upcoming Media Card js file.  Rebooted.  
On my browser, I create a private session to ensure that any cookies and cache aren't accessed.  I've tried FF and Chrome.
I have checked that the sensor.sonarr_upcoming_media etc. have the deep_link data in them - that's been there since I started trying this yesterday.
HACS continues to give me the warning that I'm ignoring:
```
Removed repository 'custom-components/sensor.sonarr_upcoming_media'
Repository is archived
```
I ignore it to ensure that I don't tell it to delete those files.

I create a new view (type Masonry (default) card with only the following in it:
```
title: TV
type: custom:upcoming-media-card
entity: sensor.sonarr_upcoming_media
image_style: fanart
collapse: flag=true
sort_by: number
enable_transparency: true
```
Which looks like this:
![image](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/1946361/f8a53379-3176-48fe-95e2-ff56d2f65c1a)

But the cursor doesn't change nor is anything clickable.  I've also tried adding the URL: http://myserver.etc.etc:5055 to test if the overall click ability works to take it somewhere, but that doesn't do anything either.

Finally, I tried it on my iphone and nothing happens.

Are there additional files I need to install besides the one .js one and to edit the ui-lovelace.yaml file?

**Comment by douginoz** [comment] 2024-03-21 05:41
I'm starting to think that I need to wait until you update everything including the instructions.  I think they're too old to follow and I'm not expert enough to work out what I should really be doing to get this working with the 2024 versions of HA.  I'll be more comfortable adding things the supported way via HACS etc rather than this manual way, which introduces so many questions and opportunities to get it wrong.

**Comment by mkanet** [comment] 2024-03-21 07:31
Have you checked to see if the rest of the new features I added to Upcoming Media Card work or not?  There are 5 more features.  If none of them work, that's your problem.  It would mean you're using an old version of Upcoming Media Card.  If all the new features work, except for deep_links; then, I will try to reproduce it in order provide a fix.

Let me know..

**Comment by douginoz** [comment] 2024-03-21 10:25
I tried enabling transparency but didn't see any difference at the time.  I wasn't sure if that was because my background is black and there's nothing to bleed through, or because it wasn't working.

As I wrote previously, I've completely removed the upcoming media card files as well as the sonarr/plex/radarr sensor files and folders, and rebooted.  I've now added them back in by doing exactly this:

1. created folder sonarr_upcoming_media in the custom_components folder.  That folder has a dozen other custom components in it so I'm sure it's the right location.  When I use the Terminal addon to get to a prompt, the path is /root/config/custom_components/sonarr_upcoming_media
2. created folder radarr_upcoming_media and plex_recently_added folders in the same location
3. copied the 3 files __init__.py, manifest.json, and sensor.py from the file links in the readme's.  So for the sonarr one, it's [here](https://github.com/custom-components/sensor.sonarr_upcoming_media/tree/master/custom_components/sonarr_upcoming_media).  (After rebooting, there's a new __pycache__ in these folders)

Then to install the upcoming-media-card I followed the instructions in it's readme [here](https://github.com/custom-cards/upcoming-media-card).  However, some of the instructions are very old and probably don't work now.  But it's all I have so I have no choice but to do what they instruct:

5. created the folder 'custom-lovelace' under the www folder (/root/config/www).  Other folders in www include 'community', 'images', and 'upcoming-media-card-images',
6. created the folder 'upcoming-media-card' within this new folder
7. copied and created 'upcoming-media-card.js'.  The full path is /root/config/www/custom-lovelace/upcoming-media-card/upcoming-media-card.js.  I used [this](https://github.com/custom-cards/upcoming-media-card/blob/master/upcoming-media-card.js) version. 
8. edited the ui-lovelace.yaml file that I found in config (/root/config).  Other folders in this config folder include blueprints, custom_components, image, python_scripts, node-red, ssh, themes, and www.  configuration.yaml is also there.  The entire  contents of my file is simply:

```
resources:
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
    type: js
```
I read this explanation of where this file is located and I think I have the right location; but it appears that this file isn't used much any more because it's all done via the UI.  That may be why mine is essentially empty.
9. I get stuck at the next instruction: 

```
This goes into one of your views under "cards:" in the same file:

  - type: custom:upcoming-media-card
    entity: sensor.sonarr_upcoming_media
```
I don't know where that's supposed to go; my ui-lovelace.yaml file only has the lines in it I pasted above.  There's nowhere for these new lines to go.

At that point I'm stuck.  After rebooting, trying to create the card again results in the error "Custom element doesn't exist: upcoming-media-card".

Rather than spend another several hours over several days poking at this, which is what I've invested, I really can't keep just trying blindly to get this working.  I think you're probably so familiar with your code and your setup that you are making some assumptions that don't apply to a brand new installation.  Certainly, the instructions for upcoming-media-card are outdated and don't work on new systems.

It would be much better for me and other people wanting to install this to wait for this to be properly available in HACS so that the installation is automatically done to the right places with the right files.

**Comment by mkanet** [comment] 2024-03-22 03:52
> This time, I added the repository but using the category 'Lovelace' rather than as an 'Integration'.During installation it said: `When downloaded this will be located in '/config/www/community/upcoming-media-card'`
> 
> And now it works!

Glad you got it working!  There is one important bugfix I need to upload in the next day or so; along with providing a respective new version on the official UMC repo.  It will be the version that people will use when it's on HACS.  Ill let you know once its ready.  Sorry for all the hassle.

**Comment by taw123** [comment] 2024-03-30 21:42
Thanks again. So as someone who dosen’t  actively use to many HACS components…

given I was using the OLD components and never removed them will your update when it goes live show us as a potential update (and thus clear the msg about the repo is deleted) allowing me to update via normal approach or will I have to do something else when you slot back into HACS?  I know I am a VERY corner case…..

😆

**Comment by mkanet** [comment] 2024-03-30 23:36
@taw123 Please don't kill me.  I just realized that all this time I forgot to change the version of this integration in the manifest file; which is definitely needed for HACS to detect you have a new version update.  I had done this for all the other integrations except for this.  I'm not sure how it would affect your case though since its still not available on HACS yet.

Anyway, give it a shot. maybe that's what was needed to nudge it into working for you.

**Comment by rosarch** [comment] 2024-04-04 19:38
Apologies for highjacking the thread, if my issues is not related I will delete and create a new one,

I'm struggling with installing this at the minute, I had no issues with the plex upcoming media integration, my issue feels related to this thread, sorry if it isn't.

When I follow the instructions and add the yaml to the configurations file and restart I get the following error:

```
The sonarr integration does not support YAML configuration
The sonarr integration does not support configuration via YAML file. You may not notice any obvious issues with the integration, but any configuration settings defined in YAML are not actually applied.

To resolve this:

If you've not already done so, [set up the integration](https://home.devoidclown.com/config/integrations/dashboard/add?domain=sonarr).

Remove sonarr: from your YAML configuration file.

Restart Home Assistant.
```

I decided to see if installing Sonarr and using sensor.sonarr_upcoming from it would work, but If I add a media card with the following config
```
type: custom:upcoming-media-card
entity: sensor.sonarr_upcoming
title: Upcoming TV
```

I get this error.
`"undefined" is not valid json`

Any ideas?

**Comment by mkanet** [comment] 2024-04-05 03:44
> I decided to see if installing Sonarr and using sensor.sonarr_upcoming from it would work, but If I add a media card with the following config
> 
> ```
> type: custom:upcoming-media-card
> entity: sensor.sonarr_upcoming
> title: Upcoming TV
> ```
> 
> I get this error. `"undefined" is not valid json`
> 
> Any ideas?

Hi @rosarch it doesn't sound like you're doing it right.  It's a lot easier for me to just show you below.  It only takes a few seconds.   
Hopefully, below is all you need to do.  Let me know...

![Overview – Home Assistant - Google Chrome 2024-04-04 20-37-27](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/811008/b0fb6b75-a75e-40de-be88-8c084f7c55f2)

**Comment by rosarch** [comment] 2024-04-05 11:00
Thanks @mkanet, I have worked out my issue, it was a clash in the configuration.yaml with the Plex integration. I temporarily removed the plex configuration and it works fine now. I just need to update it to incorporate both of them.

**Comment by FuzzyMistborn** [comment] 2024-04-11 13:32
Maybe I'm missing something, but HACS is still complaining that the repo(s) are archived.

![image](https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/16689090/89bc13a2-af01-43c6-ae18-5808ede39d97)

**Comment by mkanet** [comment] 2024-04-11 16:34
> Maybe I'm missing something, but HACS is still complaining that the repo(s) are archived.

I can confirm this happens to me too.  There is a list of archived repos that HACS keeps track of which unfortunately doesn't change until these repos are officially added to HACS.  I am still anxiously waiting for my PRs to be approved by HACS repo moderators.

Just to be safe, I think I'll open an issue on the HACS repo to double-check that the above will happen automatically.  If there is another quicker way to do it, I'll find out.

**Comment by mkanet** [comment] 2024-04-11 16:34
I am reopening this issue for others to see.

**Comment by taw123** [comment] 2024-04-12 17:36
<_Apologies for the length_> 
The "solution/workaround" for me (and my sanity) with a number of these has been to MANUALLY add the custom Repo(s) to HACS AFTER removing any/ALL installed (forked/offically recognized) versions of these related integrations/lovelace components.

If I did NOT remove them it "seemed" like I CONTINUED to get the other- much OLDER, forked versions, of these components. These were/are very old versions that were forked by others during the time that these components were listed as "archived" and others in some cases steeped up to fork/support them.


### For example.... Take the case of **Plex Recently Added:**
This was forked and "supported" _per HACS_ by NemisisRE. At some point over the years I actually moved over to it as it looked like this was the path to continued updates to the component given the maykar archive announcement. In other cases where there was no one who took over, I just kept the original integration/cards (which actually was the genesis of this original bug/issue)

While moving to this new repo resolved the ... "Repo is archived" log msgs, and for a period I think might have actually provided several updates, it is **far** behind what has been done here at what I consider to be true Head of tree (even if HACS might not). This led to HACS shooting BOTH repos as the "source" with 2 very different code bases. The integration info page HACS brings up for SOME of these components clearly lists BOTH Repos in the header (see below) with not clear indication WHICH one is ACTUALLY installed. You could however look at the info data and date of last update too tell it REALLY was the old version (with last update of last year)

<img width="1788" alt="Plex recently added component info- both shown without  custom Repo" src="https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10588252/598e15e5-272f-491c-b2d1-a0813dc4b319">


Now that folks have been kind enough to pick these back up, we have the potential to return to the canonical source repos for these components. But due to the either the craziness of HACS (or MUCH more likely may poor understanding of it's use and internals), combined with the fact that Maykar's PRs haven't yet been accepted leads to a case were his "updates" are not yet seen as upgrades for the forks. Thus the need to "force"(?) to use his Repo is the source for your HACS installation. If not I kept getting the option ONLY to install the OLD version from last year.

So I went to and added the listed repo(s) to the HACS custom repos per below:
- Plex Recently Added: custom-components/sensor.plex_recently_added _(integration)_ 
- Radarr Upcoming Media: custom-components/sensor.radarr_upcoming_media _(integration)_
- Sonarr Upcoming Media: custom-components/sensor.sonarr_upcoming_media _(integration)_
- Upcoming Media Card: custom-cards/upcoming-media-card _(plugin)_

<img width="749" alt="Manually added Custom Repos" src="https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10588252/7f7d2851-583d-4615-bffb-f85bd317b456">


This then results in several less than ideal outcomes (that I will list) BUT does seem to ensure that you have installed the DESIRED/most current/supported version of the component(s) from the original author. It ALSO SHOULD mean that as they are updated you will get those updates/version control.... VERY IMPORTANT

1. You will/may see the same integration listed twice in the HACS store.....  First the "official/old" version and then your manually aded custom repo source. 
<img width="1225" alt="With (Custom Repo) custom-components:sensor plex_recently_added- Both listed" src="https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10588252/dd16d7dc-53b9-45f5-8351-85477e0f5e43">

2. Also since you have added a Repo source that is "advertising(?)" a component for which the OFFICIAL HACS store THINKS it has you may also still see these messages that the Repo has been archived (or perhaps this is just what was stated above that HACS is maintaining a list of all repos that WERE ever archived and my efforts here had nothing to do with my messages) 
<img width="848" alt="Repo archived" src="https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10588252/34714ab1-d31d-4b20-a3a8-8d820ce7c12d">


Hopefully in time all of this will work it's self out as all four of these become the canonical reference in HACS which should potentially solve both the duplicate listings AND the warning about archived components which were caused by the forked components using the same identifiers as the original now UNARCHIVED components. Thanks again to ALL who helped...  The original and not active authors, AS WELL AS those who forked and tried to help fill a gap.

And as was said above HOPEFULLY this helps someone who actually read all of this. If you are just scanning and jumped to the end (no judgement). 

1. Remove ALL versions of the "old"/official" HACS versions (reboot)
2. Manually add reference to the "New"/current versions of those you want to HACS via the custom repo
3. Manually download the components from those repos you just added.
4. Ignore msg about Repo being archived
5. Thank, Star, and support the relevant devs how made this possible!   😀

**Comment by mkanet** [comment] 2024-04-12 20:14
Thanks @taw123 that's pretty much what I've been doing.  I just received confirmation from a HACS moderator that this will clear automatically once these repos are officially added to HACS.


https://github.com/hacs/integration/issues/3625#  _"It will be automatic"_

**Comment by taw123** [comment] 2024-04-20 20:51
Not sure if I should qualify this as a "bug" but...

HomeAssistant today informed me that: 
`The sonarr_upcoming_media platform for the sensor integration does not support platform setup. Please remove it from your config.`

Seems YAML config has been deprecated in the move to config flow?

So I commented out my the config in my config.yaml, rebooted and proceeded to add through UI as it seems that the EXISTING config wasn't migrated to to the new config_UI. Took me a couple guesses to get it right as of course I/we are ahead of any documentation of the ui (via HACS or the local repo) so I'll offer the follow as a hint for anyone else attempting to use...


If you want to keep your existing dashboards and ui configs simple add it back with NO hostname and the entity will again have the name sensor.sonarr_upcoming_media except it will now be "upgraded"/recreated(?) as a full-fledged HA citizen with unique ID. In the case of this sensor, it wasn't critical for ME that data continuity be preserved in logging/recorder, so I didn't fully check to see if the entity ATTRIBUTES remained continuous across the platform/config_UI change but the entity has and that's ok for me.

I looks like the other media_card feeding integrations I mentioned above still use the classic platform/config.yaml.

Is this also expected to change for your Radarr integration?     
<img width="688" alt="Upcoming MediaCard integrations" src="https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10588252/7320e373-c8e3-4d95-9158-68aef5d873c5">


**Looking good!**
<img width="1608" alt="ConfigUI Integration" src="https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10588252/53bc12df-5f88-4396-8f55-4e6be86caa9b">

**Comment by taw123** [comment] 2024-04-30 16:08
@mkanet Applogies for the interruption.
Quick question that think is relevant in this thread, and thus I hope at _potentially_ reasonable to post in a bug...

Does the FULL version release of [Radarr_UpcomingMedia](https://github.com/custom-components/sensor.radarr_upcoming_media/releases/4.0.0)  mean now that one can remove ALL versions off that integration through HACS (and the corresponding workaround of the custom repo), reboot, then ADD it back again through HACS and not have to deal with the archived message in the logs?

It would SEEM to me that since the version NOW exceeds the previous version strings that this should resolve the issue of getting the wrong integration assuming it's now "fully blessed" by HACS (or whatever they call their certification process).
<img width="1287" alt="Radar upcoming" src="https://github.com/custom-components/sensor.sonarr_upcoming_media/assets/10588252/9f06aeaa-1e6d-4cac-b001-d0e37a526c9e">



I'm posting it here as if this IS correct then I would expect the same process should be followed for those who have posted here when you have an opportunity to update Sonarr_upcoming

**Comment by taw123** [comment] 2024-05-01 01:50
NP... and thanks for getting back to me.

I have set ignored slo fortunately I don't have to deal with them in the main UI, but of course they are still present in the log as I deal with other issues ;)

**Comment by mkanet** [comment] 2024-05-01 02:54
Yeah, its pretty annoying for me to see that message too.  Hopefully, the HACS moderators will get to approving these repos soon.  Its already been about a couple of months.

**Comment by arsenicks** [comment] 2024-05-08 21:10
> Yeah, its pretty annoying for me to see that message too. Hopefully, the HACS moderators will get to approving these repos soon. Its already been about a couple of months.

Hi,

Just wanted to chip in to be sure you guy's know this. The problem right now is the radarr et sonarr_upcoming_media repos are still in the "blacklist" as listed here: https://github.com/hacs/default/blob/master/blacklist#L100

It has been done two years ago with this PR for plex, radarr and sonarr: https://github.com/hacs/default/commit/cb2dfebe9832b75eef79cb0e9149a5714bfe83fe

I wasn't able to understand why plex_upcoming_media was still working while being in the blacklist:   https://github.com/hacs/default/blob/master/blacklist#L96 Untill I figured someone else added his fork in 2022.. https://github.com/hacs/default/pull/1382

So I don't know, maybe it would be simplier to first be removed from the blacklist in another PR and at the very least people adding the repo manually will not face the archived repo error while we wait for HACS to accept your latest PR ?

**Comment by mkanet** [comment] 2024-05-30 18:08
Guys, Im going to close this issue since there isn't anything that can be done until HACS moderators approve these integrations (and UMC) to be back on HACS again.

As stated earlier, these repos will automatically be removed from the "archived repos list" that they maintain:
https://github.com/hacs/integration/issues/3625#issuecomment-2052459097

**Closed by mkanet** 2024-05-30 18:08 UTC
