### ISSUE TITLE
TV Show image are not loading

### ISSUE THREAD

**Issue by jnavarrodev** [custom-components/sensor.sonarr_upcoming_media#12] opened 2019-11-17 15:17 UTC
**Describe the Bug**
TV shows image are not showing. The image points to thetvdb.com web. For example, for a watchmen episode it is:
https://www.thetvdb.com/banners/_cache/posters/5d85d693a958a.jpg

When accessing to that url, this is the response:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>2157C07AEC485B3A</RequestId>
<HostId>
1ySluSzRG+IBP53NpBPgqZZWKSj7s6aghvMs8frAQJ4Qz/icasdad5yPQHL6OuWldWmXXXzgfUKxJ4=
</HostId>
</Error>
```

Sonarr Upcoming Media component version: 0.2.1
Upcoming Media Card version: 0.4.0
HA version: 0.101.3

Is something wrong with my configuration? I also have the Plex Recently Added installed and works fine (but the images point to local resource like /local/custom-lovelace/upcoming-media-card/images/plex/XXX.jpg)

**Comment by maykar** [comment] 2019-11-17 17:04
This is apparently an issue with thetvdb's API and has only been reported on their forums yesterday so there doesn't appear to be any helpful responses yet, but I'll keep an eye on it.

https://forums.thetvdb.com/viewtopic.php?f=118&t=60150&p=163354&hilit=_cache#p163354

**Comment by maykar** [comment] 2019-11-17 20:05
Looking through their forums it seems as if their whole API has been having issues for the past few days.

**Comment by DavidFW1960** [comment] 2019-11-22 23:49
Kodi has just updated their addon to use the new API. I think the issue is it's changed to https now

**Comment by maykar** [comment] 2019-11-24 19:43
Looks like the URL for thumbnail images just changed from "/_cached/"  to adding a "_t" before the ".jpg" will have a fix up soon.

**Comment by maykar** [comment] 2019-11-26 15:39
Images URLs have been fixed in the latest release. If you're still having issues it's probably related to http/https issues. You can see if this is the issue by pressing F12 and seeing this error in your dev console `ERR_BLOCKED_BY_CLIENT`.  You could access your HA using a remote URL with https or add a cert for https to HA or the only other fix for this would be for me to rewrite this integration to download images like the Plex component does. Right now I've got my hands full with the rewrite of Compact Custom Header and some other things, but this is on my list.

**Closed by maykar** 2019-11-26 15:39 UTC
